import Shared from "./shared";
import Pages from "./pages";

const {
	Projects,
	Footer,
	ScrollAlert,
	Banners,
	Nav,
	Radio,
	DarkRadialGradient,
	ModalWrapper,
	Layout,
	Noise,
	ProjectModal,
	Logo,
	Common,
	ScrollToTop,
	SectionPlaceholder,
	BannerCurtain,
	Spinner,
	AlternatingOpacity,
	ProgressBar,
	ProjectsViewSelector,
	Slider,
	ProjectsFilterModal,
	RouteTransitionOverlay,
	Preloader,
	PostCard,
} = Shared;

const { HomePage, SingleProject } = Pages;
const { Thoughts, Work, Skills, FaintBgText, ProjectsHeading, Creativity } = HomePage;

export {
	Thoughts,
	Banners,
	Layout,
	Work,
	Skills,
	FaintBgText,
	ProjectsHeading,
	Creativity,
	SingleProject,
	Projects,
	Footer,
	ScrollAlert,
	Nav,
	Radio,
	DarkRadialGradient,
	ModalWrapper,
	Noise,
	ProjectModal,
	Logo,
	Common,
	ScrollToTop,
	SectionPlaceholder,
	BannerCurtain,
	Spinner,
	AlternatingOpacity,
	ProgressBar,
	ProjectsViewSelector,
	Slider,
	ProjectsFilterModal,
	RouteTransitionOverlay,
	Preloader,
	PostCard
};
